apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: 249458120008.dkr.ecr.us-east-1.amazonaws.com/backend-app:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: backend-app
      imagePullSecrets:
        - name: regcred