name: Build backend app and deploy

defaults:
  run:
    working-directory: "backend/app/"

on:
  push:
    branches:
    - feature/backend-app
    paths:
    - 'backend/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  BuildAndDeploy:
    name: Build backend app and deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: | 
        apt-get update && apt-get -y install maven
        mvn clean package package
        ls -l
        ls -l target/