name: Apply Terraform manifest

defaults:
  run:
    working-directory: "iac/"

on:
  push:
    branches:
    - feature/aws-vpc

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"
  PRIVATE_KEY_ARN: "arn:aws:secretsmanager:us-east-1:249458120008:secret:default-key-private-bYvAni"

jobs:
  TerraformApply:
    name: Apply Terraform manifest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6

    - name: Terraform Init
      run: terraform init

    - name: Connect to Bastion Host
      run: |
        sudo apt-get update && sudo apt-get -y install sshuttle
        aws secretsmanager get-secret-value --secret-id $PRIVATE_KEY_ARN --query SecretString --output text > ~/aws.pem
        chmod 400 ~/aws.pem
        cat ~/aws.pem
        sshuttle -r ubuntu@54.167.201.143 10.10.0.0/24 -vv --ssh-cmd 'ssh -i ~/aws.pem'

    - name: Terraform apply
      run: terraform apply --auto-approve
      continue-on-error: false