name: Apply Terraform manifest for k8s private resources

defaults:
  run:
    working-directory: "private-iac/"

on:
  push:
    branches:
    - feature/backend-app
    paths:
    - 'private-iac/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"
  PRIVATE_KEY_ARN: "arn:aws:secretsmanager:us-east-1:249458120008:secret:default-key-private-DPJUOI"

jobs:
  TerraformApplyPrivate:
    name: Apply Terraform manifest for private k8s resources
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6

    - name: Terraform Init
      run: terraform init

    - name: Connect to Bastion Host
      run: |
        sudo apt-get update && sudo apt-get -y install sshuttle
        aws secretsmanager get-secret-value --secret-id $PRIVATE_KEY_ARN --query SecretString --output text > ~/aws.pem
        chmod 400 ~/aws.pem
        cat ~/aws.pem
        sshuttle -r ubuntu@34.235.144.50 10.10.0.0/24 -vv --ssh-cmd 'ssh -i ~/aws.pem  -o StrictHostKeyChecking=accept-new' &
        sleep 20

    - name: Terraform apply
      run: terraform apply --auto-approve
      continue-on-error: false