name: Validate Terraform code

defaults:
  run:
    working-directory: "iac/"

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  TerraformValidate:
    name: Validate Terraform on PRs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.4

    - name: Terraform fmt
      run: terraform fmt -check
      continue-on-error: false

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate -no-color